spring:
  application:
    name: azhur-katering-backend-java

  # ========================================
  # DATABASE CONFIGURATION (Production)
  # ========================================
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate  # Только валидация в production
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

  # ========================================
  # FLYWAY MIGRATION CONFIGURATION (Production)
  # ========================================
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    out-of-order: false
    clean-disabled: true  # Запрещаем очистку в production

  # ========================================
  # EMAIL CONFIGURATION (Production)
  # ========================================
  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${YANDEX_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail.smtp.auth: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH}
      mail.smtp.ssl.enable: true
      mail.smtp.starttls.enable: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE}
      mail.smtp.connectiontimeout: 10000
      mail.smtp.timeout: 10000
      mail.smtp.writetimeout: 10000

# ========================================
# JWT CONFIGURATION (Production)
# ========================================
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:900000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}

# ========================================
# SERVER CONFIGURATION (Production)
# ========================================
server:
  port: ${SERVER_PORT:8080}

# ========================================
# LOGGING (Production)
# ========================================
logging:
  level:
    root: WARN
    azhue.katering: INFO
    org.springframework.security: WARN
    org.springframework.web: WARN
    # Отключаем автоматическое логирование исключений Spring Boot
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: ERROR
    org.springframework.web.servlet.mvc.support.DefaultHandlerExceptionResolver: ERROR