global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'azhur-katering-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: 'azhur-katering-backend'
          environment: 'development'
    scrape_interval: 30s
    scrape_timeout: 10s

# Alerting (опционально)
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093
